In [40]:
#soham : 25070123170
#Experiment 9

In [41]:
#Why Numpy?
#Faster Than Lists
#Used For Numerical computation
#Base For Pandas

# ***Declaration of Numpy***




In [42]:
#Declaration of Numpy
import numpy as np

a= np.array([1,10,20,30.5,40,50,500])
b= np.array([[1,2,3],[4,5,6]])

print(a)
print(b)



#Dimention of matrix
print("Dimention of a:",a.ndim)
print("Dimention of b:",b.ndim)


#Size of the matrix
print("Size of a: ",a.size)
print("Size of b: ",b.size)

#Shape of Matrix
print("Shape of a: ",a.shape)
print("Shape of b: ",b.shape)

#Datatype
print("Datatype of a: ",a.dtype)
print("Datatype of b: ",b.dtype)

print(b*2)
print(a+5)


[  1.   10.   20.   30.5  40.   50.  500. ]
[[1 2 3]
 [4 5 6]]
Dimention of a: 1
Dimention of b: 2
Size of a:  7
Size of b:  6
Shape of a:  (7,)
Shape of b:  (2, 3)
Datatype of a:  float64
Datatype of b:  int64
[[ 2  4  6]
 [ 8 10 12]]
[  6.   15.   25.   35.5  45.   55.  505. ]


# ***In-bulit functions using Numpy***


In [43]:
#In-bulit functions using Numpy
np.zeros((2,3))



array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.ones((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [47]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [48]:
print(np.mean(a))

93.07142857142857


In [49]:
print(np.median(a))

30.5


In [50]:
print(np.max(a))

500.0


In [51]:
print(np.min(a))

1.0


In [52]:
print(np.sum(a))

651.5
